### ISSUE TITLE
BlazorWorker.Demo.IoCExample error

### ISSUE THREAD

**Issue by xibaoning** [Tewr/BlazorWorker#52] opened 2021-05-17 08:24 UTC
MyIocService.cs 
try
            {
                await this.WorkerMessageService.PostMessageAsync($"aaaaaaa"); // error
                return this.AServiceDependency.Five();
            }
            finally
            {
                if (this.FiveCalledCounter > 2)
                {
                    await this.WorkerMessageService.PostMessageAsync($"{nameof(FiveCalledCounter)} has been called more than 2 times: {this.FiveCalledCounter} times!"); //  error
                }
            }

//////////////////////////////error message
dotnet.5.0.4.js:1 Uncaught Error: System.AggregateException: One or more errors occurred. (Unexpected character encountered while parsing value: F. Path '', line 0, position 0.)
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: F. Path '', line 0, position 0.

**Comment by Tewr** [comment] 2021-05-17 09:10
Hello. This looks lika a duplicate of #51

**Closed** 2021-05-18 19:30 UTC
Labels: duplicate
