### ISSUE TITLE
Send array [] to webworker

### ISSUE THREAD

**Issue by Sigve84** [Tewr/BlazorWorker#50] opened 2021-04-08 06:36 UTC
I am trying to send an image array to a webworker from Blazor C#. 

//Blazor
 `await service.RunAsync(s => s.ImageAquired(imageBytes));`

// Web worker
```
 public class FrequencyFinderService {
        public void ImageAquired(byte[] image)
        {
           // do stuff with the image
        }
    }

```

The problem is that the transfer of the image from Blazor to Webworker takes too much time. It locks up the UI. Is there a way to do this in an efficient manner?

I had a similar problem to get the image from  JS to Blazor, but that solution was to use the "JSUnmarshalledRuntime.InvokeUnmarshalled"
` var image = JSUnmarshalledRuntime.InvokeUnmarshalled<byte[]>("WebCamFunctions.snap");`

**Comment by Tewr** [comment] 2021-04-09 05:34
Hello. Thank you for your feedback.

Transferring a dot net array to the worker unmarshalled is not trivial. I'm pretty sure it's possible but mono-wasm marshalling is not very well documented so i haven't been able to figure it out. This library exclusively uses marshalling over a string, as it is really the only trivial data type to send over the process border unmarshalled. 

That said, to keep your ui from freezing up, you could use a stream instead of transferring a large byte array all at once. Again, there currently no native support for streams, so you would have to implement the transport yourself. 

Built-in support for streams in the backgroundservice layer is tracked in issue #3 .

**Comment by Sigve84** [comment] 2021-04-09 10:33
Thanks for the reply.

It seems that the performance to send base64 to a js worker has much better performance vs going through blazer.

Just to rule out that it does not work, I am trying to send a base64 string to worker.PostMessageAsync. The issue is that I am receiving 

"WASM-WORKER: 
Uncaught Error: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: d. Path '', line 0, position 0"

how should I format the text in worker.PostMessageAsync?


```

await worker.PostMessageAsync("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAoAAAAHgCAYAAAA10dzkAAAgAElEQVR4XqSd63ojSY5kI0hKWdUzs7vv/6AzVZm87AfADgBHBKWsafWP6pTIuPjV3GAw7NePj9fr9dy27bLt+2W77q9t3/ftuu2b/dxfz+3xeGyXi/19316vx/a0z78u/rvba9fv7W+v7RFf2/bLy/+9v7bNr/+6+e+f22W7Xq9+nfjcwz/H37f97tezH74fV4wff1T92PPuF93wdYnr7He/Hx+7vfq3t227fsRzPH/5fx+vlz/Pbb9sj+cznlXPGTf83C77ZXtdXn6v5/2/xwXrn9Yel9fH9nw+tufOE8R/7W/Pp/3/m1/PWiJ+Lt6e9jt778djz/9v7";);
               




// Web worker
public class FrequencyFinderService {

        private readonly IWorkerMessageService messageService;
        public static FrequencyFinder _frequencyFinder = new FrequencyFinder();

        public FrequencyFinderService(IWorkerMessageService workerMessageService) {
            messageService = workerMessageService;

            this.messageService.IncomingMessage += OnMessage;
        }

      
        private void OnMessage(object sender, string message)
        {
            Console.WriteLine("image " + images);
        }
    }
```

**Comment by Tewr** [comment] 2021-04-09 11:21
assuming you are using the higher abstraction, The BackgroundService package, your message is expected to be a json serialization of the [MethodCallParams](/Tewr/BlazorWorker/blob/master/src/BlazorWorker.WorkerBackgroundService/MethodCallParams.cs) class. Sending messages directly from js will be very fragile, and I think youll have a hard time tracking service instance ids and whatnot.

If you really want to go down this road I'd suggest you use the BlazorWorker.Core package instead. The Core package does not use any serialization other than some extremely crude csv-ish messages for service instanciation, and any type of message sent on the message bus will be accepted.

That said, I think your code looks fine. We are probably looking at a bug here: messages that does not deserialize should be ignored by the message parser rather than throwing an error. Your scenario used to work, so to me this is a regression.

**Comment by Tewr** [comment] 2021-08-03 16:55
I'm closing this due to lack of activity

**Closed by Tewr** 2021-08-03 16:55 UTC
