### ISSUE TITLE
BlazorWorker does not work in net6 with published release

### ISSUE THREAD

**Issue by semyonc** [Tewr/BlazorWorker#69] opened 2022-01-13 12:12 UTC
Hello,
it seems that BlazorWorker does not support net6 publishing.

For example, if you create a project with the standard ASP.NET Core hosted blazor Web assembly template and replace 
Index.razor with BackgroundServiceMulti.razor for using example code everything works fine in the Debug and Release mode 
from Visual Studio.

But after dotnet publish -c Release
if you start the compiled server app
you will see:

![image](https://user-images.githubusercontent.com/667990/149327827-b5de17ad-3556-4c2c-a005-e97393647fd4.png)

**Comment by Tewr** [comment] 2022-01-13 16:24
This is probably related to trimming, I don't think there is any trimming going on before publish

**Comment by Tewr** [comment] 2022-01-18 22:03
From https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options:

> The default TrimMode for Microsoft.NET.Sdk is link in .NET 6+, and copyused in previous versions.

So to still use trimming, but a lot less aggressively, I've successfully tried the directive `<TrimMode>copyused</TrimMode>`,  instead of `<PublishTrimmed>false</PublishTrimmed>`.

**Comment by semyonc** [comment] 2022-01-19 08:35
But still not working if RunAOTCompilation = true

![image](https://user-images.githubusercontent.com/667990/150093698-d915aff3-633b-45c5-a8f3-51da8c2f7669.png)

**Comment by Tewr** [comment] 2022-01-19 12:14
No I would be very suprised if that worked out of the box, AOT being very reflection-sensitive and I'm not even sure if the bootloader looks the same when using aot.

**Comment by Tewr** [comment] 2022-02-01 23:06
So I've been debugging AOT build, it's horribly slow to iterate on, as each rebuild takes about 15 mins.

I've specified all dependencies to be sure that it's not a missing dep that has been introduced, it changes the error slightly.

I get the following error instead: 
<code>

    Init method [BlazorWorker.WorkerBackgroundService]BlazorWorker.WorkerBackgroundService.WorkerInstanceManager:Init failed RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info. at abort (dotnet.6.0.1.ugq34bq9rf.js:1:13873)
    at _abort (dotnet.6.0.1.ugq34bq9rf.js:1:97000)
    at dotnet.wasm:0x27c919e
    at dotnet.wasm:0x2264a7e
    at dotnet.wasm:0x2264a42
    at dotnet.wasm:0x244b6a1
    at dotnet.wasm:0x1b2e84
    at dotnet.wasm:0x278eab5
    at invoke_vi (dotnet.6.0.1.ugq34bq9rf.js:1:262301)
    at dotnet.wasm:0x2928772
</code>


I've subsequently managed to track it down to 
<code>this.serializer.Serialize(obj)</code>

from here:

https://github.com/Tewr/BlazorWorker/blob/3453903be5ff4ad7ebe6770233ef1f607011ea9e/src/BlazorWorker.WorkerBackgroundService/WorkerInstanceManager.cs#L63

The underlying serializer is Newtonsoft. I might be able to get around this with a library trimmer config but it's a very slow process and there is no guarantee of success.

A long-term solution, which is something I thought about anyway, is to get rid of a majority of the reflection code in this library and replace it with source code generators. It could boil down dynamically called code to a single entry point method on the worker process. This would also dramatiacally decrease message size and speed up calls.

**Comment by marcin-golebiowski** [comment] 2022-02-07 21:35
I hope I'm not wrong but it seems that the issue is not connected with Newtonsoft. I've replaced it with System.Text.Json and I have the same issue when running with AOT.

**Comment by Tewr** [comment] 2022-02-07 22:14
System.text.json has a source code generator mode which does not use reflection, this is what I was thinking of. But indeed, the core example does not use either, and it didn't seem to work in AOT mode either. I think it's important to get the core example working first before focusing on anything else, to understand what is wrong. Perhaps decorating the SimpleInstanceService with the correct AOT attributes  is enough...

**Comment by floribe2000** [comment] 2022-03-31 22:36
We ran into the same issue when using link trimming mode on .NET 6. By coincidence we found a possible workaround, I am not sure if it will work in all cases but it solved the problem for us:
```
<ItemGroup>
    <TrimmerRootAssembly Include="System.Private.CoreLib" />
    <TrimmerRootAssembly Include="System.Security.Cryptography.X509Certificates" />
</ItemGroup>
```
System.Private.CoreLib was apparently the main issue as it was trimmed a lot before. The second lib needed to be added because it was completely stripped by the trimmer, I am not sure if there is another way to prevent that other than adding it as root assembly for the trimmer.
After this change, app download size increased by around 300-500 MB (depending which compression method is used) but it's still smaller than in "copyused" trimmer mode.

**Comment by StachuDotNet** [comment] 2022-06-01 13:58
FWIW, we've been able to load+run an AOT wasm build (.net 6) in a web worker. We hacked a previous version of `blazor.webassembly.js` to not reference `window` so much.

- Here's the F# side: https://github.com/darklang/dark/blob/main/fsharp-backend/src/Wasm/Wasm.fs
- Here's the hacked loader: https://github.com/darklang/dark/blob/d3bf74ff70ba3701cdc9f9181ae60894daa70e0a/fsharp-backend/src/Wasm/static/BlazorWorker.js#L931
- Here's the usage: https://github.com/darklang/dark/blob/d3bf74ff70ba3701cdc9f9181ae60894daa70e0a/client/src/appsupport.js#L242`

Just noting it here in case it's useful to someone.

**Comment by Tewr** [comment] 2024-05-02 08:21
This seems to be fixed with .net8. feel free to reopen if you can see indications of the contrary

**Closed by Tewr** 2024-05-02 08:21 UTC
Labels: Compatibility
